# Generated by Django 2.2.4 on 2019-08-03 23:05

import authentication.managers
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(error_messages={'unique': 'Пользователь с таким номером телефона уже существует'}, help_text='Необходимо заполнить это поле.', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть введен в следующем формате: '+77123456789'", regex='^\\+77\\d{9}$')], verbose_name='номер телефона')),
                ('last_name', models.CharField(help_text='Необходимо заполнить это поле.', max_length=30, verbose_name='фамилия')),
                ('first_name', models.CharField(help_text='Необходимо заполнить это поле.', max_length=30, verbose_name='имя')),
                ('patronymic', models.CharField(blank=True, max_length=30, verbose_name='отчество')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='адрес электронной почты')),
                ('gender', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], help_text='Необходимо заполнить это поле.', max_length=1, verbose_name='пол')),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now, help_text='Необходимо заполнить это поле.', verbose_name='дата рождения')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации')),
                ('national_id', models.CharField(help_text='Необходимо заполнить это поле.', max_length=9, validators=[django.core.validators.RegexValidator(message='Ввведите 9-ти значный номемер удостоверени личности пользователя', regex='\\d{9}')], verbose_name='номер удостоверения личности')),
                ('abonement_type', models.IntegerField(choices=[(0, 'Абонемент недействителен'), (1, 'Абонемент на кол-во посещений'), (2, 'Абонемент на заданный период'), (3, 'Аюонемент сотрудника')], default=0, verbose_name='тип абонемента')),
                ('abonement_registration_date', models.DateField(auto_now=True, verbose_name='дата регистрации абонемента')),
                ('abonement_visits_left', models.IntegerField(choices=[(0, 'Не указано'), (1, '1 посещение'), (5, '5 посещений'), (10, '10 посещений'), (15, '15 посещений'), (30, '30 посещений')], default=0, help_text='Необходимо заполнить это поле.', verbose_name='посещений доступно')),
                ('abonement_validity_period', models.IntegerField(choices=[(0, 'Не указан'), (1, '1 месяц'), (3, '3 месяца'), (6, '6 месяцев'), (12, '1 год')], default=0, help_text='Необходимо заполнить это поле.', verbose_name='период действия')),
                ('is_active', models.BooleanField(default=True, verbose_name='activeness status')),
                ('is_staff', models.BooleanField(default=True, verbose_name='staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', authentication.managers.UserManager()),
            ],
        ),
    ]
