# Generated by Django 2.2.4 on 2019-08-09 08:23

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20190807_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ('date',)},
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='time',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='portrait',
            field=models.ImageField(upload_to=authentication.models.content_file_name, verbose_name='фото'),
        ),
    ]
