# Generated by Django 2.2.4 on 2019-08-11 03:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20190809_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ('date',), 'verbose_name': 'посещение', 'verbose_name_plural': 'посещения'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='abonement_visits_left',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 3, 12, 49, 410377), verbose_name='дата посещения'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='side',
            field=models.IntegerField(choices=[(0, 'Вход'), (1, 'Выход')], default=0, verbose_name='направление'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='user',
            name='abonement_type',
            field=models.IntegerField(choices=[(0, 'Абонемент недействителен'), (1, 'Абонемент на заданный период'), (2, 'Абонемент сотрудника')], default=0, verbose_name='тип абонемента'),
        ),
    ]
